GET http://localhost:3000/api/cars
####
GET http://localhost:3000/api/cars/1
####
DELETE http://localhost:3000/api/cars/2
####
POST http://localhost:3000/api/cars
Content-Type: application/json

{
  "foo": "bar"
}
####